networks:
  charlymatloc.net:
    driver: bridge

services:
  # Backend: Slim PHP Application
  api.charlymatloc:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - '6080:80'  
    volumes:
      - ./app:/var/php  
    working_dir: /var/php
    networks:
      - charlymatloc.net
    depends_on:
      - charyoutils.db  
    command: sh -c "composer install && php -S 0.0.0.0:80 -t /var/php/public" 

  # PostgreSQL database for backend
  charyoutils.db:
    image: 'postgres:latest'
    env_file: ./charyoutils.env  
    ports:
      - '5432:5432'  
    networks:
      - charlymatloc.net
    volumes:
      - ./sql:/var/sql  

  # HTML frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend  
    ports:
      - "8080:80"  
    volumes:
      - ./html:/var/www/html  
    networks:
      - charlymatloc.net

  # Adminer for SQL management
  adminer:
    image: adminer
    ports:
      - '8081:8080'  
    networks:
      - charlymatloc.net
